language: node_js
sudo: false
node_js:
  - "12.14.0"
  
install:
  - yarn
before_install:
  - npm i -g hexo@3.9.0 
  - npm i
script:
  - hexo g

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  local-dir: public
  target-branch: master
  verbose: true
  on:
    branch: src
