language: node_js
sudo: false
node_js:
  - "8"

before_install:
  - npm i -g hexo
script:
  - hexo g

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: false
  name: jiangtao
  local-dir: public
  target-branch: master
  verbose: true

  on:
    branch: src
